services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ai-media2doc-backend:local
    env_file:
      - "variables.env"
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8081:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ai-media2doc-frontend:local
    deploy:
      mode: replicated
      replicas: 1
    environment:
        - VITE_API_BASE_URL=http://localhost:8081
    ports:
      - "5173:5173"
